### ISSUE TITLE
Altitude calibration on flight node startup

### ISSUE THREAD

**Issue by jellosubmarine** [jellosubmarine/droonituuled#10]
/mavros/vfr_hud tends to be not publishing, fix was to calibrate altitude in QGroundControl. Need to implement this in code, probably through some service or find a workaround.

**Comment by jellosubmarine** [comment]
https://discuss.ardupilot.org/t/solving-barometer-drift/6172

**Comment by johankytt** [comment]
Results from testing:
- Not a barometer problem. Pixhawk is not publishing anything on mavros topics. Attaching and disconnecting QGroundControl (without doing anything else there) fixes the problem until the next power cycle.
- Setting GPS_TYPE = 0 (none), GPS_TYPE2 = 0 (none), EK2_GPS_TYPE = 3 (inhibit) has no effect

Might be that Pixhawk wants a 3d fix and QGC automatically provides it upon connection.

**Comment by jellosubmarine** [comment]
http://forum.erlerobotics.com/t/ros-topics-not-publishing-anything/142

You need to set the stream rate:

`rosservice call /mavros/set_stream_rate 0 10 1`

or if you are using C++:

```
ros::NodeHandle n;
ros::ServiceClient client = n.serviceClient<mavros::StreamRate>("/mavros/set_stream_rate");
mavros::StreamRate srv;
srv.request.stream_id = 0;
srv.request.message_rate = 10;
srv.request.on_off = 1;
if(client.call(srv)){
    ROS_INFO("Service called");
}else{
    ROS_INFO("Failed to call service");
}
```

**Comment by johankytt** [comment]
Moved the code added by Rando to main(). Seems to work, not tested on hardware.
